name: school_absence_app
description: Szybka aplikacja do zgłaszania nieobecności dziecka w szkole

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Ikony aplikacji
  assets:
    - assets/
